CONTIKI_PROJECT = sybil-attack
all: $(CONTIKI_PROJECT)

CONTIKI = ../../../..
CONTIKI_TARGET = z1

MODULES += os/net/ipv6
MODULES += os/net/rpl

PROJECT_SOURCEFILES += sybil-attack.c

include $(CONTIKI)/Makefile.include

