CONTIKI_PROJECT = security_module
all: $(CONTIKI_PROJECT)

CONTIKI = ../../../..
CONTIKI_TARGET = z1

MODULES += os/net/ipv6
MODULES += os/net/rpl

PROJECT_SOURCEFILES += security_module.c

include $(CONTIKI)/Makefile.include

