CONTIKI_PROJECT = rpl-security
all: $(CONTIKI_PROJECT)

CONTIKI = ../../../..
CONTIKI_TARGET = z1

MODULES += os/net/ipv6
MODULES += os/net/rpl

PROJECT_SOURCEFILES += rpl-security.c

include $(CONTIKI)/Makefile.include

